import { IColumn } from '@/lib/types';

export const OrderColumns: IColumn[] = [
  { uid: '1', label: 'Захиалгын дугаар' },
  { uid: '2', label: 'Нийлүүлэгч' },
  { uid: '3', label: 'Статус' },
  { uid: '4', label: 'Захиалгын зураг' },
  { uid: '5', label: 'Захиалгын огноо' },
  { uid: '6', label: 'Хүргүүлэх огноо' },
  { uid: '7', label: 'Захиалгын дүн' },
  { uid: '8', label: 'Төлөгдсөн дүн' },
  { uid: '9', label: 'Төлбөрийн хэлбэр' },
  { uid: '10', label: 'Купон' },
  { uid: '11', label: 'Тэмдэглэл' },
  { uid: '12', label: 'Утасны дугаар' },
  { uid: '13', label: 'Харилцагчийн нэр' },
  { uid: '14', label: 'Суваг' },
  { uid: '15', label: 'Хот/аймаг' },
  { uid: '16', label: 'Дүүрэг/сум' },
  { uid: '17', label: 'Хороо/Баг' },
  { uid: '18', label: 'Дэлгэрэнгүй хаяг' },
  { uid: '19', label: 'Pickpack' },
  { uid: '20', label: 'Origin' },
  { uid: '21', label: 'VAT' },
  { uid: '22', label: 'ХТ код/нэр' },
  { uid: '23', label: 'Түгээгч код/нэр' },
  { uid: '24', label: 'Агуулах' }
];

export const ProductsColumns: IColumn[] = [
  { uid: '1', label: 'ID' },
  { uid: '2', label: 'Show' },
  { uid: '3', label: 'Нийлүүлэгч' },
  { uid: '4', label: 'Image' },
  { uid: '5', label: 'Name' },
  { uid: '6', label: 'Vendor' },
  { uid: '7', label: 'Ангилал' },
  { uid: '8', label: 'Дэлгэрэнгүй' },
  { uid: '9', label: 'Үлдэгдэл' },
  { uid: '10', label: 'Зохистой хэмжээ' },
  { uid: '11', label: 'Аюулгүйн нөөц' },
  { uid: '12', label: 'Min_order qty' },
  { uid: '13', label: 'Sup_min order' },
  { uid: '14', label: 'Хүргэлтийн өдөр' },
  { uid: '15', label: 'Barcode' },
  { uid: '16', label: 'SKU' },
  { uid: '17', label: 'PPID' },
  { uid: '18', label: 'Price' },
  { uid: '19', label: 'Сагслах тоо' },
  { uid: '20', label: 'Хотын татвар' },
  { uid: '21', label: 'Бутархайгаар сагслах' },
  { uid: '22', label: 'Pickpack' },
  { uid: '23', label: 'Устгах' },
  { uid: '24', label: 'Дэлгүүр тохируулах' }
];
