import { IColumn } from '@/lib/types';

export const OrderColumns: IColumn[] = [
  { uid: 'id', label: 'Захиалгын дугаар' },
  { uid: '123', label: 'Trade shop ID' },
  { uid: 'supplierId', label: 'Нийлүүлэгч' },
  { uid: '4', label: 'Захиалгын зураг' },
  { uid: '3', label: 'Захиалгын төлөв' },
  { uid: 'orderedAt', label: 'Захиалсан өдөр' },
  { uid: 'deliveryDate', label: 'Хүргүүлэх өдөр ' },
  { uid: '7', label: 'Захиалгын дүн' },
  { uid: '8', label: 'Төлөгдсөн дүн' },
  { uid: '11', label: 'Тэмдэглэл' },
  { uid: '14', label: 'Бизнесийн суваг' },
  { uid: '12', label: 'Утасны дугаар' },
  { uid: '13', label: 'Харилцагчийн нэр' },
  { uid: '15', label: 'Хот/аймаг' },
  { uid: '16', label: 'Дүүрэг/сум' },
  { uid: '17', label: 'Хороо/Баг' },
  { uid: '18', label: 'Дэлгэрэнгүй хаяг' },
  { uid: '101', label: 'Бүсчлэл' },
  { uid: '9', label: 'Төлбөрийн хэлбэр' },
  { uid: '10', label: 'Купон' },
  { uid: '102', label: 'Захиалгын эх үүсвэр' },
  { uid: '22', label: 'Худалдааны төлөөлөгийн код' },
  { uid: '23', label: 'Түгээгчийн код' },
  { uid: '19', label: 'НӨАТ' },
  { uid: '20', label: 'Буцаалт' },
  { uid: '21', label: 'Шуурхай түгээлт' },
  { uid: '24', label: 'Агуулах' }
];

export const ProductsColumns: IColumn[] = [
  { uid: 'id', label: 'Ебазаар бүтээгдэхүүний ID' },
  { uid: 'isActive', label: 'Active' },
  { uid: 'customer.name', label: 'Нийлүүлэгч' },
  { uid: 'name', label: 'Бүтээгдэхүүний нэр' },
  { uid: 'barCode', label: 'Баркод' },
  { uid: 'sku', label: 'Бүтээгдхүүний SKU' },
  { uid: 'images.0', label: 'Зураг' },
  { uid: 'brand.name', label: 'Брэнд' },
  { uid: 'categories.2.name', label: 'Ерөнхий ангилал' },
  { uid: 'categories.1.name', label: 'Дэд ангилал' },
  { uid: 'categories.0.name', label: 'Эцсийн ангилал' },
  { uid: 'description', label: 'Бүтээгдэхүүний дэлгэрэнгүй' },
  { uid: 'inventory.totalStock', label: 'Үлдэгдэл' },
  { uid: 'adjustedPrice.price', label: 'Үнэ' },
  { uid: 'inventory.availableStock', label: 'Сагслах тоо' },
  { uid: 'inCase', label: 'Хайрцаган дахь тоо' },
  { uid: 'isAlcohol', label: 'Алкохолны төрөл эсэх' },
  { uid: 'cityTax', label: 'Хотын татвар төлөх эсэх' }
];

export const CustomerColumns: IColumn[] = [
  { uid: '_id', label: 'Харилцагчийн нэр' },
  { uid: 'id1', label: 'Утасны дугаар' },
  { uid: 'id2', label: 'Худалдааны цэгийн нэр' },
  { uid: 'id3', label: 'Худалдааны цэгийн ерөнхий  байршил' },
  { uid: 'id4', label: 'Худалдааны цэгийн байршил' },
  { uid: 'id5', label: 'Худалдааны цэгийн газарзүйн координат' },
  { uid: 'id6', label: 'Аж ахуйн нэгжийн төрөл' },
  { uid: 'id7', label: 'Худалдааны цэгийн суваг' },
  { uid: 'id8', label: 'Худалдааны цэгийн үндсэн ангилал' },
  { uid: 'id9', label: 'Худалдааны цэгийн үйл ажиллагаа эхлүүлсэн огноо' },
  { uid: 'id12', label: 'Хот/Аймаг/сонголтоор/' },
  { uid: 'id13', label: 'Дүүрэг/Сум/сонголтоор/' },
  { uid: 'id14', label: 'Хороо/Баг/сонголтоор/' },
  { uid: 'id15', label: 'И-мэйл' },
  { uid: 'id16', label: 'Дэлгэрэнгүй хаяг' },
  { uid: 'id17', label: 'Тусгай зөвшөөрөл' },
  { uid: 'id18', label: 'Хариуцсан ХТ код' }
];
