apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-office-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back-office
  template:
    metadata:
      labels:
        app: back-office
    spec: 
      containers:
        - name: back-office
          image: 1stnano/back-office:latest
          env:
            - name: AUTH_SECRET
              value: 'QrVIQFJ7di+sanZQKQtmV1BgnaTuqx+tfNwwS0yGIG0='
            - name: MEDIA_URL
              value: https://m.ebazaar.mn/media
            - name: MEDIA_URL
              value: https://m.ebazaar.mn/upload
            - name: AUTH_TRUST_HOST
              value: http://localhost:3000
            - name: API_URL
              value: https://pro.ebazaar.mn/api/v1
            - name: NODE_ENV
              value: 'production'
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /login
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
---
apiVersion: v1
kind: Service
metadata:
  name: back-office-srv
spec:
  selector:
    app: back-office
  ports:
    - name: back-office
      protocol: TCP
      port: 3000
      targetPort: 3000